spring.application.name=usuario-microservico

server.port=8082
# URL base do UBS-microservico
# se não estiver rodando no Render,
# cai pra http://localhost:8083
ubs.service.url=${UBS_SERVICE_URL:http://localhost:8083}

medicamento.service.url=${MEDICAMENTO_SERVICE_URL:http://localhost:8080}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

