# application.yml  (estrutura correta)

spring:
  application:
    name: Ubs-Microservico

  datasource:
    url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.zapxzqrggnsqgbfjvtrl
    password: MedmapParaUbs
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


  sql:
    init:
      mode: always            # só se tiver scripts .sql

server:
  port: 8083

# ---- URLs de outros micro‑serviços (fora de spring / server!) ----
auth-service:
  url: http://localhost:8081
medicamento-service:
  url: http://localhost:8080

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET:UmSegredoMuitoForte12345678901234567890123456789012}
  expiration: ${JWT_EXPIRATION:3600}  # ← Adicione isso aqui
